/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Pinder
 */

 public class Mainpage extends javax.swing.JFrame {
public static int counter=0;
public static int counta=0;
 int i=-1;
 int x=-1;
    /**
     * Creates new form Mainpage
     */
    public Mainpage() {
         this.setTitle("Quiz");
  counter++;
        initComponents();
              this.setLocationRelativeTo(null);
              if(counter!=1)
              {Quiz.questionNo=1;
              Quiz.counter=0;
              Quiz.countero=0;
              jButton3.doClick();
              }
              else
        jButton3.doClick();
              try{ 
           Quiz.getAnswer();}
    catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(990, 680));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 40, 970, 120));

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.setToolTipText("");
        jRadioButton1.setPreferredSize(new java.awt.Dimension(141, 70));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 170, 410, 70));

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.setToolTipText("");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 510, 70));

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton3.setText("jRadioButton3");
        jRadioButton3.setToolTipText("");
        jRadioButton3.setPreferredSize(new java.awt.Dimension(141, 70));
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 410, 80));

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("jRadioButton4");
        jRadioButton4.setToolTipText("");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 520, 80));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 70, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 450, 390, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 10, 80, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("as");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 390, 120, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pinder\\Desktop\\thumb-1920-438082.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1030, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        counta++;
         
        try {
            if(Quiz.questionNo>40)
            {
                JOptionPane.showMessageDialog(this, "This is the last question");
              this.setVisible(false);
              new Homepage().setVisible(true);
            }
             i++;
           
                while ( i!=0 )
                { x++;
                    if(jRadioButton1.isSelected() )
                    
                {//check=0;
                    System.err.println(jRadioButton1.getText());
                    System.err.println(x);
                    System.err.println(Quiz.ans[x]+".");
                    if(jRadioButton1.getText().contains(Quiz.ans[x]+"."))
                { JOptionPane.showMessageDialog(this, "Your answer is correct");
                //score=score+10;
                //jLabel3.setText("Your score is : "+MainPage.score);
                break;
                }else
                {   JOptionPane.showMessageDialog(this, "Oops, your answer is wrong.");
                //jLabel3.setText("Your score is : "+MainPage.score);
                break;
                } }
                else  if(jRadioButton2.isSelected()  )
                { //check=0;
                    System.err.println(jRadioButton2.getText());
                    System.err.println(Quiz.ans[x]+".");
                       if(jRadioButton2.getText().contains(Quiz.ans[x]+"."))
                       { JOptionPane.showMessageDialog(this, "Your answer is correct");
                       //score=score+10;
                       //jLabel3.setText("Your score is : "+score);
                       break;} 
                       else{
                    JOptionPane.showMessageDialog(this, "Oops, your answer is wrong.");
                     //jLabel3.setText("Your score is : "+score);
                break;}
                }else if(jRadioButton3.isSelected() )
                { //check=0;
                     System.err.println(jRadioButton3.getText());
                    System.err.println(x);
                    System.err.println(Quiz.ans[x]+".");
                        if(jRadioButton3.getText().contains(Quiz.ans[x]+"."))
                       { JOptionPane.showMessageDialog(this, "Your answer is correct");
                    //    score=score+10;
                      //   jLabel3.setText("Your score is : "+score);
                        break;} 
                       else{
                            //System.out.println(answer);
                    JOptionPane.showMessageDialog(this, "Oops, your answer is wrong.");
                    // jLabel3.setText("Your score is : "+score);
                break;}
                } else  if(jRadioButton4.isSelected() )
                { //check=0;
                     System.err.println(jRadioButton4.getText());
                    System.err.println(x);
                    System.err.println(Quiz.ans[x]+".");
                      if(jRadioButton4.getText().contains(Quiz.ans[x]+"."))
                       { JOptionPane.showMessageDialog(this, "Your answer is correct");
                    //   score=score+10;
                      //  jLabel3.setText("Your score is : "+score);
                       break;} 
                       else{
                    JOptionPane.showMessageDialog(this, "Oops, your answer is wrong.");
                     //jLabel3.setText("Your score is : "+score);
                break;}
                }  
                    else
                {  // if( count!=0)
                
                   JOptionPane.showMessageDialog(this,"Please select an answer");
                //check=1;
                // jLabel3.setText("Your score is : "+score);
             
                break;
                }}
            Quiz.getQuestion();
           Quiz.getOptions();
          
         
          
          
        } catch (IOException ex) {
            Logger.getLogger(Mainpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO - add your handling code here:
        this.setVisible(false);
        new Homepage().setVisible(true);
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JRadioButton jRadioButton3;
    public static javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
